services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    env_file:
      - .env.dev
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
    env_file:
      - frontend/.env.development
    ports:
      - 3000:3000
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - db-store:/var/lib/postgresql/data
volumes:
  db-store:
